apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: gsapkar/multi-server
          ports:
            - containerPort: 5000 #container port is mapped to the multi-client image
          env:
            - name: REDIS_HOST # we put the name of the redis culster-ip-service
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: PG_USER
              value: postgres
            - name: PG_HOST # name of the postgres cip cluster service
              value: postgres-cluster-ip-service
            - name: PG_PORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
